/*
 * 
 * “Commons Clause” License Condition v1.0
 * 
 * The Software is provided to you by the Licensor under the License, 
 * as defined below, subject to the following condition.
 * 
 * Without limiting other conditions in the License, the grant of rights under the License 
 * will not include, and the License does not grant to you, the right to Sell the Software.
 * 
 * For purposes of the foregoing, “Sell” means practicing any or all of the rights granted 
 * to you under the License to provide to third parties, for a fee or other consideration 
 * (including without limitation fees for hosting or consulting/ support services related to 
 * the Software), a product or service whose value derives, entirely or substantially, from the 
 * functionality of the Software. Any license notice or attribution required by the License 
 * must also include this Commons Clause License Condition notice.
 * 
 * Software: genestrip
 * 
 * License: Apache 2.0
 * 
 * Licensor: Daniel Pfeifer (daniel.pfeifer@progotec.de)
 * 
 */
package org.metagene.genestrip.fastqgen;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;

import org.metagene.genestrip.io.StreamProvider;
import org.metagene.genestrip.store.Database;
import org.metagene.genestrip.store.KMerStore;
import org.metagene.genestrip.store.KMerStore.IndexedKMerStoreVisitor;
import org.metagene.genestrip.tax.SmallTaxTree;
import org.metagene.genestrip.tax.TaxTree;
import org.metagene.genestrip.util.CGAT;

/**
 * Generates a FASTQ file from a k-mer store database by decoding each stored k-mer back into bases
 * and writing it as a read, optionally restricted to a given tax id (and its descendants).
 */
public class KMerFastqGenerator {
	/** FASTQ read descriptor prefix identifying reads generated by Genestrip. */
	public static final String GENESTRIP_ID = "@GENESTRIP";

	// private final Database database;
	private final KMerStore<SmallTaxTree.SmallTaxIdNode> kmerStore;
	private final byte[] data;

	/**
	 * Creates a generator over the k-mer store of the given database.
	 *
	 * @param database the database whose k-mer store is used as the source of reads
	 */
	public KMerFastqGenerator(Database database) {
		//this.database = database;
		this.data = new byte[database.getKmerStore().getK()];
		kmerStore = database.convertKMerStore();
	}

	/**
	 * Generates a FASTQ file at the given path from the matching stored k-mers.
	 *
	 * @param file     the file to write the FASTQ output to
	 * @param taxid    the tax id to restrict output to, or null for all tax ids.
	 * @param header   the header string included in each read's descriptor.
	 * @param withDesc if true, a k-mer's node also matches when {@code taxid} is one of its ancestors.
	 * @throws IOException if writing the output file fails
	 */
	public void generateFastq(File file, String taxid, String header, boolean withDesc) throws IOException {
		try (OutputStream out = StreamProvider.getOutputStreamForFile(file)) {
			generateFastq(out, taxid, header, withDesc);
		}
	}
	
	/**
	 * Generates FASTQ output to the given stream from the matching stored k-mers.
	 *
	 * @param out      the stream to write the FASTQ output to
	 * @param taxid    the tax id to restrict output to, or null for all tax ids.
	 * @param header   the header string included in each read's descriptor.
	 * @param withDesc if true, a k-mer's node also matches when {@code taxid} is one of its ancestors.
	 * @throws IOException if writing to the stream fails
	 */
	public void generateFastq(OutputStream out, String taxid, String header, boolean withDesc) throws IOException {
		FastQWriter fastQWriter = new FastQWriter(GENESTRIP_ID + ":" + header, out);
		fastQWriter.start();

		kmerStore.visit(new IndexedKMerStoreVisitor<SmallTaxTree.SmallTaxIdNode>() {
			@Override
			public void nextValue(KMerStore<SmallTaxTree.SmallTaxIdNode> trie, long kmer, int index, long i) {
				SmallTaxTree.SmallTaxIdNode node = kmerStore.getValueForIndex(index);
				if (isMatchingNode(node, taxid, withDesc)) {
					CGAT.longToKMerStraight(kmer, data, 0, data.length);
					fastQWriter.addRead(node.getTaxId(), data);
				}
			}
		});
		fastQWriter.done();
	}

	/**
	 * Returns whether the given node matches the tax id filter: any node when {@code taxid} is null
	 * and {@code withDesc} is set, the node itself when its tax id equals {@code taxid}, or (when
	 * {@code withDesc} is set) any node having {@code taxid} as an ancestor.
	 *
	 * @param node     the node to test
	 * @param taxid    the tax id to match against, or null for all tax ids
	 * @param withDesc if true, a node also matches when {@code taxid} is one of its ancestors
	 * @return whether the node matches the tax id filter
	 */
	protected boolean isMatchingNode(SmallTaxTree.SmallTaxIdNode node, String taxid, boolean withDesc) {
		if (taxid == null) {
			return withDesc;
		}
		else if (withDesc) {
			while (node != null) {
				if (node.getTaxId().equals(taxid)) {
					return true;
				}
				node = node.getParent();
			}
			return false;
		}
		else {
			return node.getTaxId().equals(taxid);
		}
	}
}
